### ISSUE TITLE
Sungrow SG12RT (String inverter)

### ISSUE THREAD

**Issue by Melectro1** [biemond/solaredge.modbus#148]
Hello 
I am using the SolarEdge + Growatt TCP modbus app with a Sungrow (String) SG12RT inverter and have successfully integrated the APP to read data via flow cards. However, I would like to extend the functionality by being able to send commands to the inverter, such as turning it on/off or controlling its output power.

Currently, the app only supports reading Modbus data, but I would appreciate it if there were an option to send commands, such as:

- Turn inverter on/off
- Adjust output power limits

I have recently connected the inverter via a LAN cable (fix IP address: 192.168.0.118), as I have read that this is necessary for Modbus write functionality. Having the ability to send these commands would significantly enhance the automation capabilities of my setup.

Thank you for your time and support!

**Comment by biemond** [comment]
hey,

so if you can find out how?  after that I can implement this.  maybe check the modbus read/write registers or some home assistant implementation.

**Comment by Melectro1** [comment]
Yes, sorry I misunderstood. I will return later with my results.

I found that the link didn't work from previous post, so I uploaded the pdf here: 

[ti_20230117_communication-protocol-of--residential-and-commerical-pv-grid-connected-inverter_v1.1.53_en.pdf](https://github.com/user-attachments/files/19944405/ti_20230117_communication-protocol-of--residential-and-commerical-pv-grid-connected-inverter_v1.1.53_en.pdf)

**Comment by Melectro1** [comment]
I think I need some support with this modbus App in Homey. I got a new device and it say "All Good", I got info to use flowcards, but in the advanced flow I can't find anything from Modbus App. Please tell me what to do.

**Comment by Melectro1** [comment]
I created a diagnostic report from in the modbus App: 7730d374-ce5e-4579-bcea-65240f880ba3

**Comment by Melectro1** [comment]
A small update on the information. I have managed to set an active power limit via Sungrow's iSolarCloud. The result is immediately visible as the exported power decreases to the set value. 

However, I am not able to read certain registers using the Modbus app. According to the manual, the register for Power Limitation Setting is 5008, but this only gives me the error: "This device is currently unavailable." 

I have also tried reading several other registers that could possibly contain the power limit value, but all of them give me an error. 

The Active Power Limit value shown on the device from SolarEdge + GroWatt App constantly says 100%. I had expected this value to reflect what I set in iSolarCloud. Therefore, my question is: which register address is used in the SolarEdge app?

**Comment by Melectro1** [comment]
Thank you,

I'm struggling to get the Modbus app you recommended to work, but I'm now only getting an error saying the device is unavailable. Do you have any tips? I have: restarted the inverter, removed the Homey device, and added a new one. The Ip address is static and it is answering on ping.

**Comment by biemond** [comment]
probably you can only have 1 modbus connection at the time.  and have to wait a few minutes to recover.

**Comment by biemond** [comment]
maybe remove your device and try to do modbus only and get some easy as a test.    check if it 2 or 4 bytes and holding registers or not. that are the most important params

see the registers of me.

**Comment by Melectro1** [comment]
I restarted the Home again, and for the moment I can read/write some registers.

I have now also been in contact with Sungrow support, who confirmed that to change the power limit, you first need to send 'enable' to register 5007, and then set the limit in register 5008. I also looked into your code and I think  active_power_limit: register 5001 is not the limit parameter in Sungrow SG12RT. 
If I set the limit in iSolarCloud, register 5001 (read from Homey Modbus app) still shows 1, but the inverter only delivers a maximum of 10% of 12kW, after I have sent 10%.

![Image](https://github.com/user-attachments/assets/ec10940a-0301-432a-aeaa-16306c13015f)

**Comment by Melectro1** [comment]
> active_power_limit: register 5001 (on row 31) is not the limit parameter in Sungrow SG12RT.

I believe that register 5001 is the maximum installed power. I can't read the active limit setting in register 5008, since a read from register 5008 refers to the second table shown in the manual on page 7 (internal temperature).
 
![Image](https://github.com/user-attachments/assets/1cc82cd7-fa85-48b3-8617-18873f60edef)

**Comment by biemond** [comment]
need to check but I am not doing 5008.  Did you check the holding registers ?  it should be R/W .  
and what is your inverter type?

**Comment by Melectro1** [comment]
Here is my flow, which I have verified against my own inverter. You’ll probably raise an eyebrow when you see the different starting addresses (#0 and #1), as well as the fact that I send a "1" instead of 0xAA or 0x55. In the image, you can also see that I send the value 250, which corresponds to 25.0%, and I can see that my inverter is now producing 3 kW. I’ve also sent 500, which results in 6 kW. This works!

![Image](https://github.com/user-attachments/assets/41162ce3-0005-41aa-8084-0b920b97c6bb)

![Image](https://github.com/user-attachments/assets/b3a5d95d-fe19-49a8-afcd-af25306dc27e)

**Comment by Melectro1** [comment]
My Inverter is Sungrow SG12RT, it is found under Sungrow String devices in your App

**Comment by biemond** [comment]
good , let me check the docs.  and maybe I can add it to the list and you can send me a diagnostic report.

**Comment by biemond** [comment]
got. the docs,  it is 5007 ,5008 on the holding registers , not input.

**Comment by biemond** [comment]
also I remember I had to do -1 on alll registers.   can you try to get 5001 on a input register.  UINT16.

**Comment by Melectro1** [comment]
Modbus is a bit special. My very first experience was that register addresses start at 40000, but sometimes people choose to start at either 0 or 1. Sungrow seems to have started their list at 1, so you need to subtract 1, which is also mentioned in the manual I found.

![Image](https://github.com/user-attachments/assets/c2480725-3387-4583-840c-55571074b448)

I've run my test flow with two options for the starting address (0 and 1). When I use 0, I get the contents of register 1. If I choose starting address 1, I get the value 120, which is more correct since the maximum power is 12.0 kW.

It's confusing that the manual says "Nominal active power" at register 5001, while the device window in Homey shows "Active power limit". It might be a good idea to update the wording in the Homey app.

![Image](https://github.com/user-attachments/assets/ec301867-66ed-40c9-91ae-5881b81cd8d7)

This value is constantly at 100%, and I interpret that as 100% of 12 kW. However, it's not very useful to know that the inverter can deliver 100%. Therefore, I've tried to find a register that shows the limited value, the one you write to register 5008. But I can't read anything from that table—instead, I always get results from the readable registers, and in that case, 5008 corresponds to "internal temperature".

If you know how to read register 5008 from the holding table, it would be a good suggestion to replace the current "Active power limit" with that value.

**Comment by biemond** [comment]
let me check home assistant impl.   but above is easy to make a flow action for it.

**Comment by biemond** [comment]
can you also check 5039 holding   or also try to set 5036,5037 (reactive part)

**Comment by Melectro1** [comment]
I believe it would be beneficial for many other users to have this functionality included in the Sungrow inverter's flow cards. I just remembered that a start/stop function would also be nice to have. Holding register 5006 can be used to send 0xCE to stop and 0xCF to start the inverter.

No battery or meter is installed in my system, but there is a parameter in my system:

![Image](https://github.com/user-attachments/assets/61fcc19e-5177-4bdc-b071-a8cc2ec5f803)
 

Here is my final goal:

I could otherwise achieve what I want using the existing Modbus solution, since my goal is to first fetch the spot price of electricity from the web and then make a decision—if the price is, for example, above 1 cent. In that case, the inverter should output as much as it can and sell the surplus.

However, in the past week, we have once again experienced extreme price fluctuations. The electricity price has been as low as -1.8 cents per kWh. This means I have to pay for the energy exported to the grid. With the proposed solution, I read my smart meter to see how much energy is being exported and then reduce the inverter's power limit accordingly, so that the outgoing current is as close to zero as possible. In this way, I make the inverter produce just enough to match my household consumption, avoiding any extra cost for excess energy that I can't use.

**Comment by Melectro1** [comment]
> can you also check 5039 holding or also try to set 5036,5037 (reactive part)

I can see in iSolarCloud the parameters related to 5036 and others. However, I have no idea what the current value is set to. For that reason, I don't want to change any values unless I know how to restore them after testing. When I spoke with Sungrow support, we only discussed 5006, 5007, and 5008.

**Comment by Melectro1** [comment]
I read the same register (4 times) again after 15 minutes previous info in image above and now I got 56338 when start address is set to #1. The values makes no sense to me.

**Comment by biemond** [comment]
I do this on for U32 

```
      let resultValue: string = 'xxx';
      switch (value[2]) {
        case 'UINT16':
          resultValue = response.body.valuesAsBuffer.readUInt16BE().toString();
          break;
        case 'UINT32':
          resultValue = ((response.body.valuesAsArray[1] << 16) | response.body.valuesAsArray[0]).toString();
          break;
        case 'STRING':
          resultValue = response.body.valuesAsBuffer.toString();
          break;
        case 'INT16':
          resultValue = response.body.valuesAsBuffer.readInt16BE().toString();
          break;
        case 'INT32':
          resultValue = ((response.body.valuesAsArray[1] << 16) | response.body.valuesAsArray[0] | 0).toString();
          break;
```

**Comment by Melectro1** [comment]
![Image](https://github.com/user-attachments/assets/928de5f1-0424-40df-8298-738bd7c33c52)

**Comment by biemond** [comment]
let me add all the fields for now and make a test version.

**Comment by Melectro1** [comment]
I just noticed that there is a flow card available to read from holding registers. As they say, the first thing you go blind on is your eyes! ;-)
To answer your question: the value in holding register 5039 is 120.

**Comment by Melectro1** [comment]
I received information from the phone support that sending just a 1 to 5007 is enough to enable writing to register 5008. Since I had already enabled it from the iSolarCloud app, it turns out that this setting has applied to all of my tests and the faulty information for 5007 was not executed properly in my Homey test flow.

When I now set disable on holding register 5007 in iSolarCloud, the content of holding register 5008 became 110%. From this state, I restarted finding a setting to enable the power limit from the Modbus cards in Homey, and now the logic fully matches the manual. You must send 0xAA to register 5007 with start address #1.
It seems that once 5007 has been set to active, it remains that way. Therefore, it would be a good idea to check register 5007 first before writing to 5008 (or alternatively 5039), or always set 5007 to 0xAA (170).

![Image](https://github.com/user-attachments/assets/0ed596dc-fd22-4e96-b00c-0e4191cf06b5)

**Comment by biemond** [comment]
yeah , that is the plan , always do 5007 1st ,   also make a disable flow again.
so can you make a resume about which ones you want to read and which flow actions you want with its parameter.

**Comment by Melectro1** [comment]
I can now present a flow that does the following:
If the electricity price drops below 10 öre (~1 cent), my inverter will only produce the amount of electricity needed for my own household.
If the electricity price rises above 15 öre (~1.5 cents), the limitation is removed, and the inverter produces as much as it can, with any surplus electricity being sold at the current spot price.

The power limitation of the inverter is updated whenever my energy meter (placed on the incoming line to the house) reports that consumed (incoming) electricity exceeds 0 watts, or that produced (outgoing) electricity exceeds 100 watts.
The result is that this flow keeps both incoming and outgoing power close to 0W when the spot market electricity price is too low.

My flow diagram will look even better using your cards — and who knows, maybe someone will come up with a tip on how to implement everything in a script, so the functionality takes up even less space. Scripting in Homey is something I haven’t learned yet.

![Image](https://github.com/user-attachments/assets/e576d9a6-89f3-4e82-9ca8-fdfdbfa18559)

**Comment by biemond** [comment]
1 pro tip.  always use average of a few min like 5 min. never do when power changed , you will destroy your inverter or exhaust the eeproms.

I will make the flow part. 
so what register you like to read and show on the inverter.

**Comment by Melectro1** [comment]
Thanks for the tip! I take the number of updates into account by using hysteresis. For me, it's about finding a suitable range within which the values can fluctuate without the inverter being updated too frequently with a new limitation.
Since my last post, I’ve adjusted the range to 0 W → -200 W. 
The recurring update of register 5039, in my case, will only occur during periods when the electricity price drops below my threshold — which amounts to a few hours on certain days during spring and summer.
Right now, it seems I'm getting an update roughly every 15 minutes on average.
I assume that the EEPROM should be able to handle at least 100,000 write cycles.

**Comment by biemond** [comment]
good, no clue if you have some eeprom on your inverter to store settings during reboot.  but  some can only do 4k write actions.  some inverters are not made for so many changes on dynamic prices.

**Comment by Melectro1** [comment]
I'll ask Sungrow support to be sure that I'm not destroying the inverter.

**Comment by Melectro1** [comment]
To preserve the EEPROM, register 5007, it might be best to read its contents and only write the enable value if necessary — this to follow your advice to minimize the number of write operations.

**Comment by biemond** [comment]
can you try this 1 https://homey.app/a/solaredge.modbus/test/  and send me a diagnostic report so I can see the holding registers. 

after that I can make the flows.

**Comment by Melectro1** [comment]
Hi that was quick, thank you!

After installing, the Sungrow inverter tells device not available. and here is the report: e82ff6be-bc9e-4856-b9a4-57351b9eea81

**Comment by Melectro1** [comment]
Maybe this helps:

![Image](https://github.com/user-attachments/assets/7af2aa01-db67-4c48-bdf4-66d7bf5e9e53)

**Comment by biemond** [comment]
thanks got the error

**Comment by biemond** [comment]
and a new version https://homey.app/a/solaredge.modbus/test/

**Comment by Melectro1** [comment]
Thank you, Tested and now no device error.
01251c93-9426-488d-b768-8f8f24b71235

**Comment by biemond** [comment]
does this ok ? 

```
totaldcpower 3218 0 Total DC power
nomimal_active_power 120 -1 Nominal active power
active_power_limit2 3128 0 Total active power
temperature 426 -1 temperature
pvTodayEnergy 227 -1 daily energy yield
pvMonthEnergy 227 -1 monthly energy yield
pvTotalEnergy 24529 0 total energy yield
daily_export_from_pv 0 -1 daily export from pv
daily_direct_energy_consumption 0 -1 daily direct energy consumption
power_limitation_switch 85 0 power limitation switch 0xAA Enable 0x55 Disable
power_limitation_setting 1100 -1 power limitation setting in %
power_limitation_adjustment 132 -1 Power limitation adjustment in kW

```

**Comment by biemond** [comment]
will show these  on the device and make flow actions for it 

power_limitation_switch 85 0 power limitation switch 0xAA Enable 0x55 Disable
power_limitation_setting 1100 -1 power limitation setting in %
power_limitation_adjustment 132 -1 Power limitation adjustment in kW

**Comment by Melectro1** [comment]
Do you also make an indicator, to show the real status of the inverter from H reg 5006 (stopped or run)?

**Comment by biemond** [comment]
will add it 

Start/Stop 5006 U16 0xCF (Start). 0xCE (Stop)

**Comment by Melectro1** [comment]
If you have an interest, here is my current version of Homey flow.
Summary: When limitation enabled, the flow checks if power is out of limit settings every 10 sec. If the limitation value is updated, the timer is set to wait for 2 minutes. I have also made an average calculation with a damping factor of 40%. Today I got totally about 8 writes to H register 5039, (i'm casting debug info to my Google Home). 

![Image](https://github.com/user-attachments/assets/9b6d8b87-0cc8-4e1d-87ef-f29b9a7bfc1a)

**Power average diagram:**
![Image](https://github.com/user-attachments/assets/ccd303a2-74cf-4915-ba2e-00099b9fd7b6)

**Power production and spot price**
-> between 10:00 and 17:00, the price was below 10 öre (~1 cent/kWh), negative between 11:00-16:00
![Image](https://github.com/user-attachments/assets/d83880b3-9fb0-48e9-9a6b-f2b9000873de)

**Comment by biemond** [comment]
and this 1 https://homey.app/a/solaredge.modbus/test/

new caps and flow actions.

**Comment by Melectro1** [comment]
Thanks for the update! I've now installed it and adjusted parts of my flow accordingly.

Unfortunately, I can't find a card to set the limit once the inverter has been configured with the limitation enabled. (No cards to write to H-register 5039 or 5008)

I'm also wondering if your "enable limit" card includes the full control logic shown in the attached image. Specifically, the check on register 5007 that ensures a write is only performed if 'enable' isn't already set.

Enable limit:
![Image](https://github.com/user-attachments/assets/a2630857-ad57-4fc4-bab3-b35243cab196)

Disable limit:
![Image](https://github.com/user-attachments/assets/c133d3b3-0c5c-4659-a797-beb7ba5fa4d4)

**Comment by biemond** [comment]
rest is coming.  this is step 1.   hope to do the rest today.

**Comment by biemond** [comment]
cool, but was expecting them to be populated, can you send me a report

**Comment by biemond** [comment]
found it

**Comment by biemond** [comment]
done, pushed a new version. you should be able to read the capability instead

**Comment by Melectro1** [comment]
Thank you,
I can now see the power values, but still missing the boolean info (On or OFF status)
1c0bbca5-18dc-4414-b688-be6c2b90ea8e

![Image](https://github.com/user-attachments/assets/5f6b0c48-653c-4801-993b-e493a8c31b65)

**Comment by biemond** [comment]
thanks . I see the issue indeed 

```
Error: Invalid capability (homey:app:solaredge.modbus:start_stop) value type. Expected: string. Got: object
```

**Comment by biemond** [comment]
hey, is this homeyscript?   

homey etc , is basically nodejs.  you can install it and then run it like  node aaa.js

like this https://betterstack.com/community/questions/how-to-pass-cmdline-arguments-to-node-app/

**Comment by Melectro1** [comment]
Yes it is, except for the last lines, which I'm working on to make the two values readable as tags in the flow.
![Image](https://github.com/user-attachments/assets/e67ec907-3ca0-4a02-b9a1-4d5d7f2877ba)

![Image](https://github.com/user-attachments/assets/90bfd94d-ccd4-4fe3-a470-3dac904c8b86)

**Comment by biemond** [comment]
pushed a new version for those switches

**Comment by Melectro1** [comment]
Now there are boolean indicators, but did you remove the list of values from the device icon accidentally?

![Image](https://github.com/user-attachments/assets/654233ef-5c35-4e94-850b-60a5e704e129)

**Comment by biemond** [comment]
this looks ok and expected, it is a list of values with decimal values.

**Comment by Melectro1** [comment]
The list in the icon was admittedly long and could actually include the temperature, solar power, and active power limit.

**Comment by Melectro1** [comment]
There are some extra brackets in the code and I have deliberately left some TAB characters missing.

**Comment by biemond** [comment]
if you know github you can fork my repo and do a PR back.
it is mainly this https://github.com/biemond/solaredge.modbus/blob/main/drivers/sungrow/driver.compose.json
https://github.com/biemond/solaredge.modbus/blob/main/.homeycompose/flow/actions/start_stop.json
https://github.com/biemond/solaredge.modbus/blob/main/.homeycompose/flow/actions/power_limitation_switch.json

**Comment by Melectro1** [comment]
I'm not very experienced with GitHub and don't want to mess up any files and cause problems for you, but if it's the case that I can edit and you get the chance to review before the changes are applied, I'm happy to help with some translation into Swedish.

**Comment by biemond** [comment]
you cannot mess up , you don't have any rights on my repo,  you do fork and then it is your own clone.  change it in your repo and then it will allow to make a PR back to me.

**Comment by Melectro1** [comment]
Hi Edwin,

I just noticed that when the active power limit is disabled, it still shows an old value from register 5039. When I read 5039 with my Modbus tester, I get 13.2 kW (which is 110%).

Could it be that the active power limit isn't updated anymore once the limit is disabled?

![Image](https://github.com/user-attachments/assets/07bf01ee-1968-4da4-a0e4-4c278e734131)

**Comment by Melectro1** [comment]
> Now there are boolean indicators, but did you remove the list of values from the device icon accidentally?

Today I got the list back.

![Image](https://github.com/user-attachments/assets/1fd9dbd0-01bf-477f-bfe7-b4ffe984f942)

**Comment by biemond** [comment]
I guess that was homey, did not do anything for that. 

tonight will add the remaining flow actions and capabilities.

**Comment by biemond** [comment]
can you send me a report when it is disabled.

**Comment by biemond** [comment]
for 5039 what are values you provide to the register and are you multiplying it before with 10

**Comment by Melectro1** [comment]
I'm sending the power limit x10, when 5007 is enabled. 
When 5007 is disabled, then 5039 (and 5008) automatically changes into 13.2 (110%) I'm not sending this value, they must come from some default value setting internally in the inverter. That is why I read a different value when limit is disabled.

**Comment by Melectro1** [comment]
I am not certain whether you agree with this suggestion, but I would like to propose replacing 'Total Yield' with 'Power Limit'. Total yield is a large cumulative value that changes very little from day to day in percentage terms, and in my opinion, it is not a particularly relevant value. If, instead, you display 'Active Power Limitation' on that line, the viewer receives more current and meaningful information without needing to scroll.

In the icon layout, I have marked 'Total Yield' for removal, and I would kindly request that you insert 'Active Power Limitation (W)' on that line instead, placing it directly beneath 'Solar Power'. It is, however, beneficial that 'Total Day Yield' remains visible at the bottom of the icon.

I believe you will receive a lot of positive feedback from many Sungrow users for this change. Here in Sweden, several installers have chosen this particular brand, both historically and currently.

I have already shown this setup to a few friends who also have solar installations. In fact, my neighbor just ordered a Homey and an energy meter "Slimme Leezer+" interface today in order to replicate the solution I have. Another friend expressed a bit of envy, as he has a Fronius inverter. Perhaps that’s something that could be supported in the future. I took a look at the Fronius Homey app, but it currently lacks the limitation functionality that you are now building here. However, I noticed that Fronius also uses Modbus over TCP, so perhaps it’s something you might consider implementing.

![Image](https://github.com/user-attachments/assets/d24e79e4-1ddd-49fb-8f2f-b1f7ca5af869)

**Comment by biemond** [comment]
ah ok.  

I don't control this icon layout. need to check how you can influence this.

yeah I know about Fronius and it is more can someone provide me vpn access which helps development else it is undoable

**Comment by biemond** [comment]
if you scroll do you see all values .

**Comment by Melectro1** [comment]
> if you scroll do you see all values .
Yes I do. 
Exactly, that is the purpose – to eliminate the need for scrolling. The relevant information is displayed immediately, which simplifies the user's overview. It would be highly beneficial if the two rows could be swapped, so that the Yield rows are presented in the correct top-down order: day, month, and year, rather than the current order: year, day, and month.

> it is more can someone provide me vpn access which helps development else it is undoable
I can ask my friend who has a Fronius, and I could assist him in setting up a VPN tunnel, so only that device is accessible.

At first, I thought it was a matter of the variables being sorted alphabetically by Homey, but then I see that Active Power Limit should, in that case, have been listed at the top. Therefore, it is not as I initially thought.

**Comment by biemond** [comment]
I think it is doing this order https://github.com/biemond/solaredge.modbus/blob/main/drivers/sungrow/driver.compose.json#L9

**Comment by biemond** [comment]
I can re-shulffle them but you need to re-add the device

**Comment by biemond** [comment]
can you try the new flow actions https://homey.app/a/solaredge.modbus/test/  
I will do  value  x 10 on the 2 new actions

**Comment by Melectro1** [comment]
> I can re-shulffle them but you need to re-add the device

1) The view of the values is correct, and I have verified the order against your code, confirming that it is now the same.
![Image](https://github.com/user-attachments/assets/409c3389-a8c7-4058-8e83-b94292fb9db3)

2) I have one additional request: could you modify the Power Limit switch so that instead of returning numeric values like 170 or 85, it returns a Boolean true/false? Alternatively — and preferably — it would be great to expose this as a separate condition card under “If” in the flow editor.
This would allow users to easily create automation flows based on whether the power limit is currently active. Looking ahead, I believe others will also request a similar “If” condition card for the other switch — to check whether the inverter is currently running or stopped. This would greatly improve usability and flexibility in automation scenarios.
![Image](https://github.com/user-attachments/assets/5714ef52-d633-415e-8209-2dfe5ad79042)

3) I’ve noticed that when the switch is disabled, the value of “Active Power Switch” gets updated to something that doesn’t match the content of holding register 5039, as I mentioned in a previous post. Could you check that part of the code? It’s currently confusing to see a power limit being shown when it actually doesn’t exist (set to max.).
![Image](https://github.com/user-attachments/assets/6dceb1f4-a163-4785-b854-ece5cc05e86b)

4) I’ve noticed that the language translations I previously made in several files appear to be missing. Could you please confirm whether you still have access to those changes, or if I will need to redo them? I discovered this while reviewing the text for the newly added cards.

5) I have made an attempt to review your device code, but at this point it is too complex for me to fully understand. Therefore, I would like to ask whether it is necessary to implement a separate read operation to determine if the Power Limit switch is already in the required state before issuing an update — either to set a new Active Power Limit value or to change the switch’s own state. I ask this with consideration to your earlier comment about avoiding unnecessary write operations to the holding register. Is my check needed in the flow or will it be done internally in the card  (pls. note the image)?
![Image](https://github.com/user-attachments/assets/f3becf74-da63-4dd4-87e6-c0a768e4d851)

6) My friend has responded that he is interested and would be able to provide you with access to his inverter (with help from me).  Do you have any specific preferences regarding how the VPN tunnel should be set up?

**Comment by biemond** [comment]
2 ,  I can add a flow condition with true or false.
3 I just do a pass on , the only thing I can think of that is crashes  on a value or remembers the previous value so you can do enable again.  Can you check that.  if so than you have to set this before you do disable again. 
4 did you commit your chnages on your github repository and send me a pull request back.
5 was the plan indeed to add those.
6 nice.  I am on mac, so I can openvpn, mac , cisco or , wireguard.  we can do some tests if modbus is reachable.   I know the modbus creator @RonnyWinkler   is a heavy fronius user and made that app to control it.  no clue why he did not make its own modbus fronius app.

**Comment by RonnyWinkler** [comment]
> know the modbus creator [@RonnyWinkler](https://github.com/RonnyWinkler) is a heavy fronius user and made that app to control it. no clue why he did not make its own modbus fronius app.

Yes, he is 😀
But most in Fronius is running autonomous, especially if you have a Wattpilot charger in addition.
And Fronius has a very limited set of registers to change modes. So the app would only be a copy of RestAPI data with some special settings (force charging, set Apm limits etc.) This are no casual things a user would search for I think.

So I run 2 different apps:
HA integration for getting data (and import it the right way to Homey to get shown in HomeyEnergy).
Modbus app for generic actions. I have flows for different use cases (like functions with parameter) and I can call them in automation flows.

The Modbus app was a prototype to check out Modbus possibilities. And this got a good tool for all users with unsupported devices. And I don't want to invest for an app that only a small group of users can benefit from (and don't forget support for all the request 😅).

Have a nice sunday.

**Comment by biemond** [comment]
are you running HA because then you can get more frequent values than when you use the cloud/rest api?

**Comment by RonnyWinkler** [comment]
The HA integrations offers more data. There was also the Wattpilot (ev charger) integration I use in addition. And it updates more frequently than the Homey app.
I used it first for HA energy dashboard. That's why I already have some total energy meter entities (integral helper entities) created for the dashboard. So I could easily import all needed data to Homey.

...and I'm able to define my virtual device importing with HA community app (energy settings etc.).

A Homey app would also be good, but maintaining the existing apps is enough atm.

**Comment by biemond** [comment]
published new version with these condition card and added the capabilities.

**Comment by Melectro1** [comment]
@biemond 

> 3 I just do a pass on , the only thing I can think of that is crashes on a value or remembers the previous value so you can do enable again. Can you check that. if so than you have to set this before you do disable again.

I made a fresh test with this setup:
![Image](https://github.com/user-attachments/assets/de99c31b-6ab2-4b5f-a13f-4b5d22358ef6)

and the result is:
![Image](https://github.com/user-attachments/assets/01e29c66-7e49-4b9a-a50d-d4734d606d17)

I always get 110% in register 5008 and 132 in register 5039 when register 5007 is set to disable (85). I have reviewed all available settings in iSolarCloud, but I have not found any indication that the default limit could be set to 110%.

**Comment by Melectro1** [comment]
If I recall correctly, you linked me to two or three files where I was supposed to do translations. Unfortunately, that message has disappeared, so I’m not sure which additional file is currently relevant for updating.

**Comment by biemond** [comment]
got it , nice https://github.com/biemond/solaredge.modbus/pull/150/files

**Comment by Melectro1** [comment]
Was there any other file that needed to be modified?

**Comment by biemond** [comment]
https://github.com/biemond/solaredge.modbus/blob/main/.homeycompose/flow/actions/adjustpowerlimitation.json
https://github.com/biemond/solaredge.modbus/blob/main/.homeycompose/flow/actions/powerlimitationsetting.json

https://github.com/biemond/solaredge.modbus/blob/main/.homeycompose/flow/conditions/powerLimitationSwitch.json
https://github.com/biemond/solaredge.modbus/blob/main/.homeycompose/flow/conditions/start_stop.json

https://github.com/biemond/solaredge.modbus/blob/main/.homeycompose/capabilities/activepowerlimit2.json
https://github.com/biemond/solaredge.modbus/blob/main/.homeycompose/capabilities/power_limitation_adjustment.json
https://github.com/biemond/solaredge.modbus/blob/main/.homeycompose/capabilities/power_limitation_setting.json
https://github.com/biemond/solaredge.modbus/blob/main/.homeycompose/capabilities/power_limitation_switch.json
https://github.com/biemond/solaredge.modbus/blob/main/.homeycompose/capabilities/start_stop.json

**Comment by Melectro1** [comment]
I’ve completed nine files now. I hope everything is correct and that you’ve received them all.

**Comment by Melectro1** [comment]
Now I’m surprised again. I switched the language in Homey and restarted it. Now all the values have disappeared in the image. I’ve switched back and forth between Swedish and English, and in both cases, the values are gone.
![Image](https://github.com/user-attachments/assets/e7f4c16d-b30e-48fc-a26a-6e1e9511fb30)

**Comment by biemond** [comment]
maybe restart the solaredge app,  I got your PRs thanks.  I will make a new version tonight with the swedish, now it is still on english

**Comment by Melectro1** [comment]
> maybe restart the solaredge app

I've done that too, doesn't help. I have also created a new device, didn't solve the problem.

**Comment by Melectro1** [comment]
I'm really confused. Now the values are back, I only switched back to Swedish language and restarted Homey again.

![Image](https://github.com/user-attachments/assets/387d6931-3710-42ba-9961-482356df3b37)

**Comment by biemond** [comment]
That is a homey issue, app is fine

**Comment by biemond** [comment]
published your translations

**Comment by Melectro1** [comment]
> That is a homey issue, app is fine

1. I thought so too.
2. Seem to missed some cards
![Image](https://github.com/user-attachments/assets/68d0e4f6-e5e6-4403-8a74-d55eb92f87a2)

**Comment by biemond** [comment]
weird check the version (should be  "3.0.194") , I have at least 4 flow actions and 2 conditions. 
left side are homey default ones I think .

**Comment by Melectro1** [comment]
I'm look into all files that are older, so you will get a lot of swedish translation updates, even for Sungrow inverter with battery.

**Comment by Melectro1** [comment]
Phew, I think I’ve included everything now. Please check if a file is missing.

**Comment by Melectro1** [comment]
I just noticed that a new value has been added at the bottom. This is interesting, as it now reflects what I expected to see in the Active Power Limit (APL) field. Could you apply the value 13.2 kW and have it displayed in the APL?

![Image](https://github.com/user-attachments/assets/6fda8f0f-5cca-4d5d-a6c9-79d288276af8)

**Comment by Melectro1** [comment]
I'm searching the file that has the marked text, but i can't find it. Please can you send me a link? I wish to update the translation,

![Image](https://github.com/user-attachments/assets/a9c4df0b-2a61-4f67-9e36-d02c6dc4b23c)

**Comment by biemond** [comment]
https://github.com/biemond/solaredge.modbus/blob/main/.homeycompose/capabilities/nominalactivepower.json

**Comment by Melectro1** [comment]
Thank you, update done!

**Comment by Melectro1** [comment]
I have now enabled the limitation and am reviewing the new value you added at the bottom. It accurately reflects what I expected. The current limitation is set to 1.4 kW. I am unsure of the origin of the crossed-out Active Power Limit value — it should be possible to remove it and instead display the new, correct value in that position. However, I would like to adjust the translation of the new value once you have finalized the implementation.

![Image](https://github.com/user-attachments/assets/2a44865a-9161-4108-8e3b-7205c2673d9d)

![Image](https://github.com/user-attachments/assets/bc0b909e-af4d-4d52-a545-ccc495533c6b)

**Comment by Melectro1** [comment]
Here is my current flow. It's now more compact and neater thanks to your flow cards. I will continue with further testing tomorrow — my Homey script is working well. 

The sun is about to set.

![Image](https://github.com/user-attachments/assets/0d8387fe-8487-44fc-9105-da5ce92da916)

**Comment by Melectro1** [comment]
Today is a sunny day and I’m once again reviewing the two power values presented by the Sungrow unit and iSolarCloud. I considered the possibility that the lower power value might represent AC power and the other DC power, but the image shows that the values do not align with those in iSolarCloud. Even after waiting for the values to update, the readings still differ. Perhaps my screenshot can nonetheless give you a hint that something appears inconsistent from my perspective.

![Image](https://github.com/user-attachments/assets/216d0b96-411f-48da-9ee9-81d2ca5ea0f0)

**Comment by biemond** [comment]
I am just passing on , no logic or correction behind it.  can be they know more on isolarcloud, you need to ask them.

**Comment by biemond** [comment]
Also I think you should not do disable/enable of 5007 , just keep it on and use the right values for 5008 or 5038, less changes is better  like some EMS and if you want to disable it , put it 1st back to its original values. 
in short when you start doing this you need to know what you are doing.  you know this but I guess it will be a learning for other people.

**Comment by Melectro1** [comment]
> not do disable/enable of 5007 , just keep it on

Yes, that’s exactly what I’m doing. In my flow, I check if the switch is set to disable — if so, I write to the register to set it to enable, and vice versa. This way, the logic also handles cases where register 5007 might have been updated from somewhere else. If register 5007 is already set to enable, the system won’t write the same value again. I’ve also applied this principle in my script for updating the power limit: the new limit must differ by more than 200W for register 5008 to be updated.

In normal cases, it usually results in just one enable write in the morning and one disable in the afternoon — on days when the spot price of electricity drops too low.

Today, the price is higher than my configured threshold, so the inverter is producing at full capacity. So, no write operation at all to either register 5007 or 5008.

**Comment by biemond** [comment]
do you have meters installed?  that is the best and made for batteries or export or import restrictions , on my inverter I see it adapts every few seconds and under warranty of manufacturer

**Comment by Melectro1** [comment]
Yes, I have an energy meter installed, which also updates every 5 seconds. Without it, I would not be able to achieve the desired functionality. However, it is not a Sungrow product, but based on the information I have received from them, their solution performs the same type of operations. I am curious to hear what their expert will say. 
Based on their solution, I strongly believe that the holding register can endure significantly more than 4,000 write cycles, and my estimation is that it will function reliably until the inverter eventually fails for other reasons—likely beyond 15 years.

If I make a rough estimate based on approximately 10 updates to the power limitation each time the electricity price is negative, this would currently result in around 3,000 write operations over 10 years (10 updates per day, 30 days per year, over 10 years).

By the way, what brand is your inverter?

**Comment by biemond** [comment]
ok so you have a smart meter but it is not a modbus meter which is connected to sungrow?  else we can do export restriction flows instead.

**Comment by Melectro1** [comment]
Exactly—that’s correct. My energy meter is my main billing meter, supplemented with a Dutch add-on product:
https://www.zuidwijk.com/product/slimmelezer-plus/
The reader is connected directly to my billing meter, allowing it to be read in real time via WiFi in my Homey system.

The only way I can influence the power output from the inverter is through communication via Modbus TCP/IP, whereas Sungrow uses RS485 (Modbus). This is the small difference based on the information I have received. As I have mentioned earlier, I would like to have Sungrow’s solution confirmed by one of their experts. I am currently waiting for a reply by email, and at this point, I suspect that Sungrow’s solution performs more frequent updates to the power limitation than the approach implemented in my script.

![Image](https://github.com/user-attachments/assets/8b19a2e6-881f-4c25-968d-ee6c0d814578)

In my Homey setup, I have two scripts: one runs cyclically to calculate an average value for the power my house requires, and the other checks whether the demand has changed. If a change is detected, a new power value is calculated for household consumption, and this value then forms the basis for how much the inverter should produce (i.e., production limitation).

In order for a new value to be written to holding register 5039, it must differ from the previous one by more than a set threshold. At the moment, I have configured this threshold to ±250 W, in order to avoid unnecessary writes to register 5039 (as per your advice). With this, I have created a small flow that acts as an export restriction card, and your flow cards are now very helpful for reading from and updating the inverter with new settings.

**Comment by biemond** [comment]
yep, else you only had to do  5010,5011 or 5015.

**Comment by Melectro1** [comment]
1) With their energy meter, holding register 5010 (Enable/Disable limitation) is subjected to frequent write operations each time when the electricity price changes from negative to positive and vice versa.

2) Have you considered a revision of the wording and the new sequence I suggested in a previous message, yesterday?

**Comment by Melectro1** [comment]
1) I’m sorry to report that the Power Limitation update in engineering units is not working today. I have tried writing various constant values—132, 120, and 90—but none of them are effective. 
I have created a diagnostic report: d47c766c-5908-4d17-bcef-5cc817912cbe
Here I wrote 100 (10.0 kW), but the dashboard still reports 11.1
![Image](https://github.com/user-attachments/assets/ea64ddff-aca3-461f-b14e-512580f645d9)

The flow card for percentage-based limitation has also been tested, and this card works as expected.

2) I have an interesting result to report. I conducted a test where I:

- read the contents of register 5007 = "disable" and 5039 = 132,
- then set 5007 to "enable" and 5039 to 10,
- after which I turned off the inverter and powered it back on after approximately 30 seconds.
- Upon startup, the values I read were 5007 = "enable" and 5039 = 132.

I interpret this as an indication that register 5007 is stored in some form of EEPROM or FLASH, while register 5039 resides in RAM, because the system performs its own update of this register. This would imply that writing to 5039 poses no risk, whereas unnecessary writes to 5007 should be avoided as much as possible. I am still awaiting a response from the Sungrow expert.

The logic I have implemented in my flow is generally sound, except for the fact that I currently modify 5007 each time the electricity price crosses the threshold for whether surplus export should occur or not (2 writes to 5007, each day electricity price goes below my threshold). I will revise this so that 5007 remains set to "enable" at all times and simply increase the power limit in register 5039 to its maximum value when export is desired.


3) One more thing regarding point 2 in the previous post. The reason I consider it important to change the variable description is as follows:

When selecting variables in a flow card, the current naming is confusing—as shown in the attached image. I initially assumed that the value I had selected represented the actual limit used to restrict the inverter's power output, but that turned out not to be the case.

![Image](https://github.com/user-attachments/assets/ff89e500-bc54-45c1-a502-26b2a0faa109)
![Image](https://github.com/user-attachments/assets/bc05cc37-cafd-457d-8993-63b2b8bb6964)

**Comment by Melectro1** [comment]
For the next version release, I would like you to change the power limitation in % to allow the default range of the inverter, that is 0 to 110%. Right now, it's a slider that only goes up to 100%.

**Comment by biemond** [comment]
really, was trying to avoid slider and max 100%.  let me check

**Comment by biemond** [comment]
I see  https://github.com/biemond/solaredge.modbus/blob/main/.homeycompose/flow/actions/powerlimitationsetting.json#L17 and use number as type.

**Comment by Melectro1** [comment]
I think the slider can remain, only max should be increased to 110

**Comment by biemond** [comment]
if you want to do this with a variable value does that work or using slider , human is needed?

**Comment by biemond** [comment]
nice, I pushed a new test version

**Comment by Melectro1** [comment]
1) Test result, Writing a limit with the % setting, works. Tested by writing 105% and 60%. 
2) However writing anything to the power limitation card (register 5039) does not work.

**Comment by biemond** [comment]
for 2 when you do this , can you send me report straight after.

**Comment by biemond** [comment]
did you check appendix 6

**Comment by Melectro1** [comment]
Here is the diag report: 1111873e-518c-4a82-9cc5-b8f6e33936c5
I checked, but do not understand, numbers in column 2 is not 5039. For info, I could write to 5039 with previous modbus app and there was no problem.

**Comment by Melectro1** [comment]
Right now I updated my flow to use the modbus and first I got an error, modbus server was not availible, so I had to insert a connection card. Now I got my value into 5039.

![Image](https://github.com/user-attachments/assets/4a4623da-3d76-48b9-9ec3-afc0c78cb9f3)

**Comment by biemond** [comment]
so  I do x10 already

```
      if (type == 'adjustpowerlimitation') {
        const adjustpowerlimitationRes = await client.writeSingleRegister(5038, value * 10);
        console.log('adjustpowerlimitation', adjustpowerlimitationRes);
      }

      if (type == 'powerlimitationsetting') {
        const powerlimitationsettingRes = await client.writeSingleRegister(5007, value * 10);
        console.log('powerlimitationsetting', powerlimitationsettingRes);
      }
```

**Comment by Melectro1** [comment]
Writing to 5039 with times 10 is right, as the register should handle 1 decimal. I have tested writing 9, but still no update

**Comment by biemond** [comment]
interesting with modbus it goes well .  I am doing something wrong.

**Comment by Melectro1** [comment]
I restarted my homey after I created a new device and for the moment I get the value.

I hope you understand that it is **really confusing**, looking on the dashboard as the parameter called "Active power limit" is actually the AC power that the inverter is feeding. Please you must consider a change as it is not a limit. 

Back to your previous answer, in which way will it look weird? For the moment I also read the nominal power and I find that value can be viewed by scrolling. I think most of the users know how big their inverter is, I think it is better to have the 4 first values, showing something that changes from time to time. The "Solar Power" is actually the DC Power from the panels and that value is always a bit higher than the AC Power ("Active power limit"). The difference is showing the power loss internally in the inverter, and that loss is not something I can do much about, so I don't care about the DC power. Which justifies that the DC value could also be placed further down, so that you have to scroll to see it.
I find it important to present the values that affect the evaluation of the system to the user without requiring any interaction. 
1) The output AC power, 
2) whether there is a limitation on AC output, 
3) and the temperature
 are the three main parameters that should be prioritized and visible at a glance. To see the other values, the user will need to scroll.

**Comment by Melectro1** [comment]
No, I think you may have misunderstood me. The order I'm referring to is something you've already shown you're able to change, and you even pointed out the line where you previously rearranged some values. It's in this dashboard I'm referring to (please see the attached image).

![Image](https://github.com/user-attachments/assets/10c39e12-3c85-4547-9a1e-ca13d34f7771)

I've now downloaded your code and am running it locally using the development tool Docker Desktop. I've made this change in order to test and illustrate what I'm aiming for.

Regarding "Solar Power", I noticed that this translation is also located in the same file, so I understand that this component is intended specifically for Sungrow string inverters.

Since I’ve now made a translation to Swedish, and no one has previously seen this label in that language, I assume that it means I’m free to name the text in a way that matches Sungrow’s terminology in the Modbus manual. The other languages don’t need to be changed, of course.

Here is the layout in English. Please note that I haven’t changed the naming in English – I’ve only reordered the values based on their importance, placing "Measure Power" at the top as per your request.

![Image](https://github.com/user-attachments/assets/1e27b086-557f-4a87-b038-1d469843bcbd)

I see that the Swedish translation also resolves the significant confusion I’ve had in choosing variables when working with the flow charts. This was a very welcome detail. Here is the layout in Swedish:

![Image](https://github.com/user-attachments/assets/648ccd13-b395-43e8-ae54-70aafc651d74)

![Image](https://github.com/user-attachments/assets/da958806-a071-47c4-9607-df281e1fbde8)

![Image](https://github.com/user-attachments/assets/0c0d20fd-9304-45c3-a4f7-99f9dc072cd9)

![Image](https://github.com/user-attachments/assets/07149e21-d5d3-4b23-83a9-d1125acd77f6)

Attached the used file for this test setup:
[driver.compose.json](https://github.com/user-attachments/files/20096066/driver.compose.json)

**Comment by biemond** [comment]
again, this will only work when you remove and re-add it again.  so it is not a solution for existing owners because you loose insights .  Homey has to fix this plus no one cares about this because it is a web only feature and on settings you can choose 1 attribute which you want to show here. 

with local install you can do   homey app run --remote  to see any modbus failures.

**Comment by Melectro1** [comment]
Can you at least switch the swedish translations to the new in the proposal?

**Comment by Melectro1** [comment]
> you should not look at them at all, now it has your focus because you want to know it works as expected.

Where do you look to get the latest info about devices? (I only have my computer)

**Comment by Melectro1** [comment]
>  only see this 1 attribute.

I took a look at HA and was very impressed by how sleek dashboards you could build. Homey has quite a bit of catching up to do to achieve something equally good. Unfortunately, it's difficult to get a stable HA system up and running. For a while, I had a system that ran for about two weeks before it crashed so badly I had to reinstall everything. This kept happening over and over again, which eventually made me switch to Homey.

Here is my favorite page. With a quick glance, I can see the current electricity price, the house's electricity meter, and the solar panels. 

![Image](https://github.com/user-attachments/assets/8455f479-e7d2-48f7-9ee6-51c6fc8051a2)

This is done without having to click on anything, and what would be great is simply replacing the Nominal Power — which is a constant on the inverter — with the power limit I've requested. I'm very surprised that Homey can't handle replacing that line with another value without issues arising. To learn something from this, am I understanding you correctly that if the line is changed, the old setup remains for everyone else as long as they don't remove the device and create a new one? Is it during that time before the device is replaced that the issue occurs?

You mentioned that I might need to use device actions. I've searched online about this, but I haven't found anything that helps me understand how I can move away from using a Flow and instead choose device actions. Can you give me better information?

Here is my flow script:
`// Check power limit update.
const upperPowerLimit = 0; //watt
const lowerPowerLimit = -500; //watt
const surplusPow = -(upperPowerLimit+lowerPowerLimit)/2; // watt

let myArgs = JSON.parse(args[0]);
const elPriceHigh = myArgs.elPriceHigh >0; // 0/1
const nomPower = myArgs.nomPower*10; // watt
let solarPowLim = nomPower*1.1;
log('elPriceHigh:', elPriceHigh);
log('myArgs.storedPowLim:', myArgs.storedPowLim);
if (elPriceHigh) return -1 ; // Price above threshold, no limitation

const mTE = myArgs.meterTotalElectricity; // watt
const tAP = myArgs.totalAcProduction; // watt
//const pAvg = myArgs.power_avg; // watt
const oldSolarPowLim = myArgs.storedPowLim * 1000; // watt
let hP = mTE + tAP;
let diffPower = hP - oldSolarPowLim;

if (diffPower > upperPowerLimit || diffPower < lowerPowerLimit){
  solarPowLim = Math.min(nomPower, Math.max(0, Math.floor((hP+surplusPow) / 100)))/10;
  await tag('solarPowLim', solarPowLim);
  log('solarPowLim:', solarPowLim);
} 
else {
   log('No change, return: -1:');
   return -1;
}
`

![Image](https://github.com/user-attachments/assets/386347d4-8d8d-4883-95dd-06e094960278)

**Comment by biemond** [comment]
yep , homey finally added an energy tab , before that it is was no great plus still only on mobile . sad..   reason for home automation is mainly for energy and controlling lights, airco and blinds etc

HA is complicated and for the expert , you can never can give this to your parents.   

Homey focus on the common people and that means you cannot do it all yourself.   But advanced flows are very nice compared to HA.  

I am running HA for 2 years on a cheap intel NUC with a SSD , max total 250 euro. very stable.  but my  zigbee,z-wave , bluetooth are all running on HA because the zigbee chip is very bad, Bluetooth have no reach.   with HA I use bluetooth proxies of a few euro.   Homey has those expensive satellites

**Comment by Melectro1** [comment]
I think I've found something with the new app. I'm in the process of creating a new virtual device, and here I see the option to display tags from different devices in the same box... perfect!

**Comment by Melectro1** [comment]
Yes I think this is a good way to continue. 

Right now I see that I translated the new powerlimit Eng and % to same word in swedish. I will fork a new translation to you in a couple of minutes. I see that the names must differ.

**Comment by Melectro1** [comment]
Can you see the two new updates?

**Comment by Melectro1** [comment]
What a nice feature !  Thank you for pointing on device actions. I successfully created a new box.

![Image](https://github.com/user-attachments/assets/40cd53a1-e28c-4612-8bc6-683d10cad76f)

**Comment by Melectro1** [comment]
I have a question on selecting the property Power Limitation setting in the app "Device Capabilities". This should show the limit in kW, but the value is always the same as the limit in %. I tested to select the other property but I always get the value 110.

![Image](https://github.com/user-attachments/assets/3d51fd9b-50e9-4552-b634-1b86e7cc9f58)

**Comment by biemond** [comment]
no clue https://github.com/biemond/solaredge.modbus/blob/main/.homeycompose/capabilities/power_limitation_adjustment.json
https://github.com/biemond/solaredge.modbus/blob/main/.homeycompose/capabilities/power_limitation_setting.json
https://github.com/biemond/solaredge.modbus/blob/main/.homeycompose/capabilities/activepowerlimit2.json

maybe you did not refresh . 

I don't use this anymore https://github.com/biemond/solaredge.modbus/blob/main/.homeycompose/capabilities/activepowerlimit.json

**Comment by Melectro1** [comment]
I'm continuing to test your flow cards, and once again, everything is working perfectly today. The only thing I'm missing is the latest Swedish translation, but I assume that will come when you compile the next version. 
As for Sungrow support, it seems I'm being bounced between different departments — it's terrible that I can't get an answer to a simple question. I've now been waiting for two weeks.

**Comment by biemond** [comment]
yep at least they handle your case.

for your PR please remove % or KW from the description , it is already there as an unit.

**Comment by Melectro1** [comment]
I have changed one of them in order to distinguish the variable names. I'm currently getting the same percentage value from both in the script, and I suspect the reason is that they have the same translated name.
